Ветка для проведения codereview.
rfrolov/otus_homework_02 pull request #1
Opened 2018-08-14 09:11 UTC by rfrolov

2018-08-18 12:20 UTC, Yukigaru requested changes
Общее впечатление:
Хорошо, требования выполнены, ошибок не найдено.

2018-08-18 12:20 UTC, Yukigaru commented on src/filter.cpp
> +        auto ip    = split(lines.at(0), '.');
Довольно много лишних аллокаций, но требований к производительности не было, поэтому это допустимо.

2018-08-18 12:20 UTC, Yukigaru commented on src/filter.cpp
> +            int i;
непроинициализированная переменная. далее эти случаи не упоминаю

2018-08-18 12:20 UTC, Yukigaru commented on src/filter.cpp
> +                i = -1;
здесь можно просто break

2018-08-18 12:20 UTC, Yukigaru commented on src/filter.cpp
> +            result = false;
в данном случае лучше сразу делать return false, т.к. дальнейшие проверки не имеют смысла

2018-08-18 12:20 UTC, Yukigaru commented on src/filter.cpp
> +            result = true;
по алгоритму здесь надо сразу делать return true, т.к. дальнейшие проверки уже ничего не меняют

2018-08-18 12:20 UTC, Yukigaru commented on src/filter.h
> +using params_t = std::vector<std::tuple<int, int> >;
пробел между > > уже не является необходимым

2018-08-18 12:20 UTC, Yukigaru commented on src/main.cpp
> +            params_t vec{std::make_tuple(0, 1)};
Задавать tuple для выражения требования "элемент n должен равняться x" выглядит слишком сложным. Думаю, можно сделать проще. Хотя, если это было сделано для того, чтобы научиться пользовать tuple, тогда ок.

2018-08-18 12:20 UTC, Yukigaru commented on doc/ip_filter.cpp
> +        for(std::vector<std::vector<std::string> >::const_iterator ip = ip_pool.cbegin(); ip != ip_pool.cend(); ++ip)
стоит использовать std::cend

2018-08-18 12:20 UTC, Yukigaru commented on doc/ip_filter.cpp
> +            for(std::vector<std::string>::const_iterator ip_part = ip->cbegin(); ip_part != ip->cend(); ++ip_part)
имеет смысл стоит использовать auto

2018-08-18 12:20 UTC, Yukigaru commented on test/test_main.cpp
> +    }
большое количество тестов - хорошо

2018-08-20 05:13 UTC, closed without merging

2018-09-17 06:30 UTC, Ranihilator commented
## Оценка
Александр отметил косметические замечания касательно применение скобок в шаблонах и auto переменных. Смысл нету в больших и сложных конструкциях итераторов, данную задачу неплохо выполняет auto.

Также стоит отметить на важные замечания Александра касательно не оптимальной логики работы.

Тесты полностью покрывают поставленную задачу.